<option value="Baksa">Baksa</option>
<option value="Barpeta">Barpeta</option>
<option value="Biswanath">Biswanath</option>
<option value="Bongaigaon">Bongaigaon</option>
<option value="Cachar">Cachar</option>
<option value="Charaideo">Charaideo</option>
<option value="Chirang">Chirang</option>
<option value="Darrang">Darrang</option>
<option value="Dhemaji">Dhemaji</option>
<option value="Dhubri">Dhubri</option>
<option value="Dibrugarh">Dibrugarh</option>
<option value="Dima Hasao">Dima Hasao</option>
<option value="Goalpara">Goalpara</option>
<option value="Golaghat">Golaghat</option>
<option value="Hailakandi">Hailakandi</option>
<option value="Hojai">Hojai</option>
<option value="Jorhat">Jorhat</option>
<option value="Kamrup Metropolitan">Kamrup Metropolitan</option>
<option value="Kamrup">Kamrup</option>
<option value="Karbi Anglong">Karbi Anglong</option>
<option value="Karimganj">Karimganj</option>
<option value="Kokrajhar">Kokrajhar</option>
<option value="Lakhimpur">Lakhimpur</option>
<option value="Majuli">Majuli</option>
<option value="Morigaon">Morigaon</option>
<option value="Nagaon">Nagaon</option>
<option value="Nalbari">Nalbari</option>
<option value="Sivasagar">Sivasagar</option>
<option value="Sonitpur">Sonitpur</option>
<option value="South Salmara Mankachar">South Salmara Mankachar</option>
<option value="Tinsukia">Tinsukia</option>
<option value="Udalguri">Udalguri</option>
<option value="West Karbi Anglong">West Karbi Anglong</option>